clear;

%In this code we show that the master equation reproduces bulk displacement and invasion dynamics seen in the LM. 

%Size of Lattice
M = 30;
N = 60;

%Interaction parameter
kappa = 0.01;

%Probabilities of rotation
prot1 = 0.1;
prot2 = 0.4;

%Setting up matrices
pv1 = zeros(M,N);
pv2 = zeros(M,N);
ph1 = zeros(M,N);
ph2 = zeros(M,N);

%Setting up initial conditions

%Setting up random distribution of stripes
R = randi([1,N-1],5,1);
R = unique(R);
LR = length(R);
mR = min(R);
MR = max(R);

for j = 1:LR
    if j == 1
        if rand > 0.5
            pv2(:,1:R(j)) = ones(M,R(j));
        else
            pv1(:,1:R(j)) = ones(M,R(j));
        end
    else
        if pv2(M/2,R(j-1)) == 1
            pv1(:,R(j-1)+1:R(j)) = ones(M,R(j) - R(j-1));
        elseif pv1(M/2,R(j-1)) == 1
            pv2(:,R(j-1)+1:R(j)) = ones(M,R(j) - R(j-1));
        end
    end
end

if pv2(M/2,R(end)) == 1
    pv1(:,R(end)+1:N) = ones(M,N-R(end));
elseif  pv1(M/2,R(end)) == 1
    pv2(:,R(end)+1:N) = ones(M,N-R(end));
end
%all code till here produces random stripe distribution


%setting up AB Wall for bulk displacement
% pv2(:,1:N/2) = ones(M,N/2);
% pv1(:,N/2 + 1:end) = ones(M,N/2);
% 

figure(1)
surf(pv2+ph2)
set(gca,'fontsize',20)
axis([1 N 1 M 0 1+.1])
drawnow

%Setting up growth rate kernels
vp = zeros(M,1);
vm = zeros(M,1);
for j = 1:M
    vp(j) = exp(-kappa*(M-j));
    vm(j) = exp(-kappa*(j-1));
end

hp = zeros(N,1);
hm = zeros(N,1);
for j = 1:N
    hp(j) = exp(-kappa*(N-j));
    hm(j) = exp(-kappa*(j-1));
end

%Simulation Setup

%time step
dt = 0.01;

%number of steps
NN = 2000;

%temp matrices to store values
pv1_new = zeros(M,N);
pv2_new = zeros(M,N);
ph1_new = zeros(M,N);
ph2_new = zeros(M,N);

% vidfile = VideoWriter('master_invasion','MPEG-4');
% vidfile.FrameRate = 10;
% open(vidfile);
%Simulation using Forward Euler
for k = 1:NN
    for i = 1:M
        for j = 1:N
            if(i>1 && i<M && j>1 && j<N)
                sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((vp(i-1)*pv1(i-1,j)*(1-prot1)+pv1(i-1,j)*sumvp...
                               + vm(i+1)*pv1(i+1,j)*(1-prot1)+pv1(i+1,j)*sumvm...
                               + pv1(i,j-1)*sumhp + pv1(i,j+1)*sumhm...
                               +hp(j-1)*ph1(i,j-1)*prot1 + hm(j+1)*ph1(i,j+1)*prot1)*(1-pv1(i,j))...
                               -((ph2(i-1,j)+ph1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*prot1...
                               +(ph2(i+1,j)+ph1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*prot1...
                               +(ph2(i,j-1)+ph1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*(1-prot1)...
                               +(ph2(i,j+1)+ph1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*(1-prot1))*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((vp(i-1)*pv2(i-1,j)*(1-prot2)+pv2(i-1,j)*sumvp...
                               + vm(i+1)*pv2(i+1,j)*(1-prot2)+pv2(i+1,j)*sumvm...
                               + pv2(i,j-1)*sumhp + pv2(i,j+1)*sumhm...
                               +hp(j-1)*ph2(i,j-1)*prot2 + hm(j+1)*ph2(i,j+1)*prot2)*(1-pv2(i,j))...
                               -((ph1(i-1,j)+ph2(i-1,j)+pv1(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*prot2...
                               +(ph1(i+1,j)+ph2(i+1,j)+pv1(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*prot2...
                               +(ph1(i,j-1)+ph2(i,j-1)+pv1(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*(1-prot2)...
                               +(ph1(i,j+1)+ph2(i,j+1)+pv1(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*(1-prot2))*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((hp(j-1)*ph1(i,j-1)*(1-prot1)+ph1(i,j-1)*sumhp...
                               + hm(j+1)*ph1(i,j+1)*(1-prot1)+ph1(i,j+1)*sumhm...
                               + ph1(i-1,j)*sumvp + ph1(i+1,j)*sumvm...
                               +vp(i-1)*pv1(i-1,j)*prot1 + vm(i+1)*pv1(i+1,j)*prot1)*(1-ph1(i,j))...
                               -((ph2(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*(1-prot1)...
                               +(ph2(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*(1-prot1)...
                               +(ph2(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*prot1...
                               +(ph2(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*prot1)*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((hp(j-1)*ph2(i,j-1)*(1-prot2)+ph2(i,j-1)*sumhp...
                               + hm(j+1)*ph2(i,j+1)*(1-prot2)+ph2(i,j+1)*sumhm...
                               + ph2(i-1,j)*sumvp + ph2(i+1,j)*sumvm...
                               +vp(i-1)*pv2(i-1,j)*prot2 + vm(i+1)*pv2(i+1,j)*prot2)*(1-ph2(i,j))...
                               -((ph1(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*(1-prot2)...
                               +(ph1(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*(1-prot2)...
                               +(ph1(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*prot2...
                               +(ph1(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*prot2)*ph2(i,j));
                           
            elseif(i==1 && j >1 && j< N)
                sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((...
                               + vm(i+1)*pv1(i+1,j)*(1-prot1)+pv1(i+1,j)*sumvm...
                               + pv1(i,j-1)*sumhp + pv1(i,j+1)*sumhm...
                               +hp(j-1)*ph1(i,j-1)*prot1 + hm(j+1)*ph1(i,j+1)*prot1)*(1-pv1(i,j))...
                               -(...
                               +(ph2(i+1,j)+ph1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*prot1...
                               +(ph2(i,j-1)+ph1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*(1-prot1)...
                               +(ph2(i,j+1)+ph1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*(1-prot1))*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((...
                               + vm(i+1)*pv2(i+1,j)*(1-prot2)+pv2(i+1,j)*sumvm...
                               + pv2(i,j-1)*sumhp + pv2(i,j+1)*sumhm...
                               +hp(j-1)*ph2(i,j-1)*prot2 + hm(j+1)*ph2(i,j+1)*prot2)*(1-pv2(i,j))...
                               -(...
                               +(ph1(i+1,j)+ph2(i+1,j)+pv1(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*prot2...
                               +(ph1(i,j-1)+ph2(i,j-1)+pv1(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*(1-prot2)...
                               +(ph1(i,j+1)+ph2(i,j+1)+pv1(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*(1-prot2))*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((hp(j-1)*ph1(i,j-1)*(1-prot1)+ph1(i,j-1)*sumhp...
                               + hm(j+1)*ph1(i,j+1)*(1-prot1)+ph1(i,j+1)*sumhm...
                               + ph1(i+1,j)*sumvm...
                               +vm(i+1)*pv1(i+1,j)*prot1)*(1-ph1(i,j))...
                               -(...
                               +(ph2(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*(1-prot1)...
                               +(ph2(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*prot1...
                               +(ph2(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*prot1)*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((hp(j-1)*ph2(i,j-1)*(1-prot2)+ph2(i,j-1)*sumhp...
                               + hm(j+1)*ph2(i,j+1)*(1-prot2)+ph2(i,j+1)*sumhm...
                               + ph2(i+1,j)*sumvm...
                               + vm(i+1)*pv2(i+1,j)*prot2)*(1-ph2(i,j))...
                               -(...
                               +(ph1(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*(1-prot2)...
                               +(ph1(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*prot2...
                               +(ph1(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*prot2)*ph2(i,j));
            elseif(i == M && j > 1 && j < N)
                sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((...
                               + vp(i-1)*pv1(i-1,j)*(1-prot1)+pv1(i-1,j)*sumvp...
                               + pv1(i,j-1)*sumhp + pv1(i,j+1)*sumhm...
                               +hp(j-1)*ph1(i,j-1)*prot1 + hm(j+1)*ph1(i,j+1)*prot1)*(1-pv1(i,j))...
                               -(...
                               +(ph2(i-1,j)+ph1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*prot1...
                               +(ph2(i,j-1)+ph1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*(1-prot1)...
                               +(ph2(i,j+1)+ph1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*(1-prot1))*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((...
                               + vp(i-1)*pv2(i-1,j)*(1-prot2)+pv2(i-1,j)*sumvp...
                               + pv2(i,j-1)*sumhp + pv2(i,j+1)*sumhm...
                               +hp(j-1)*ph2(i,j-1)*prot2 + hm(j+1)*ph2(i,j+1)*prot2)*(1-pv2(i,j))...
                               -(...
                               +(ph1(i-1,j)+ph2(i-1,j)+pv1(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*prot2...
                               +(ph1(i,j-1)+ph2(i,j-1)+pv1(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*(1-prot2)...
                               +(ph1(i,j+1)+ph2(i,j+1)+pv1(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*(1-prot2))*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((hp(j-1)*ph1(i,j-1)*(1-prot1)+ph1(i,j-1)*sumhp...
                               + hm(j+1)*ph1(i,j+1)*(1-prot1)+ph1(i,j+1)*sumhm...
                               + ph1(i-1,j)*sumvp...
                               +vp(i-1)*pv1(i-1,j)*prot1)*(1-ph1(i,j))...
                               -(...
                               +(ph2(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*(1-prot1)...
                               +(ph2(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*prot1...
                               +(ph2(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*prot1)*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((hp(j-1)*ph2(i,j-1)*(1-prot2)+ph2(i,j-1)*sumhp...
                               + hm(j+1)*ph2(i,j+1)*(1-prot2)+ph2(i,j+1)*sumhm...
                               + ph2(i-1,j)*sumvp...
                               + vp(i-1)*pv2(i-1,j)*prot2)*(1-ph2(i,j))...
                               -(...
                               +(ph1(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*(1-prot2)...
                               +(ph1(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*prot2...
                               +(ph1(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*prot2)*ph2(i,j));
                           
            elseif(i > 1 && i < M && j ==1)
                sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((vp(i-1)*pv1(i-1,j)*(1-prot1)+pv1(i-1,j)*sumvp...
                               + vm(i+1)*pv1(i+1,j)*(1-prot1)+pv1(i+1,j)*sumvm...
                               + pv1(i,j+1)*sumhm...
                               + hm(j+1)*ph1(i,j+1)*prot1)*(1-pv1(i,j))...
                               -((ph2(i-1,j)+ph1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*prot1...
                               +(ph2(i+1,j)+ph1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*prot1...
                               ...
                               +(ph2(i,j+1)+ph1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*(1-prot1))*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((vp(i-1)*pv2(i-1,j)*(1-prot2)+pv2(i-1,j)*sumvp...
                               + vm(i+1)*pv2(i+1,j)*(1-prot2)+pv2(i+1,j)*sumvm...
                               + pv2(i,j+1)*sumhm...
                               + hm(j+1)*ph2(i,j+1)*prot2)*(1-pv2(i,j))...
                               -((ph1(i-1,j)+ph2(i-1,j)+pv1(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*prot2...
                               +(ph1(i+1,j)+ph2(i+1,j)+pv1(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*prot2...
                                ...
                               +(ph1(i,j+1)+ph2(i,j+1)+pv1(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*(1-prot2))*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((...
                               + hm(j+1)*ph1(i,j+1)*(1-prot1)+ph1(i,j+1)*sumhm...
                               + ph1(i-1,j)*sumvp + ph1(i+1,j)*sumvm...
                               +vp(i-1)*pv1(i-1,j)*prot1 + vm(i+1)*pv1(i+1,j)*prot1)*(1-ph1(i,j))...
                               -((ph2(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*(1-prot1)...
                               +(ph2(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*(1-prot1)...
                               ...
                               +(ph2(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*prot1)*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((...
                               + hm(j+1)*ph2(i,j+1)*(1-prot2)+ph2(i,j+1)*sumhm...
                               + ph2(i-1,j)*sumvp + ph2(i+1,j)*sumvm...
                               +vp(i-1)*pv2(i-1,j)*prot2 + vm(i+1)*pv2(i+1,j)*prot2)*(1-ph2(i,j))...
                               -((ph1(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*(1-prot2)...
                               +(ph1(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*(1-prot2)...
                               ...
                               +(ph1(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*prot2)*ph2(i,j));
            elseif(i > 1 && i < M && j == N)
                 sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((vp(i-1)*pv1(i-1,j)*(1-prot1)+pv1(i-1,j)*sumvp...
                               + vm(i+1)*pv1(i+1,j)*(1-prot1)+pv1(i+1,j)*sumvm...
                               + pv1(i,j-1)*sumhp...
                               +hp(j-1)*ph1(i,j-1)*prot1)*(1-pv1(i,j))...
                               -((ph2(i-1,j)+ph1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*prot1...
                               +(ph2(i+1,j)+ph1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*prot1...
                               +(ph2(i,j-1)+ph1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*(1-prot1)...
                               )*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((vp(i-1)*pv2(i-1,j)*(1-prot2)+pv2(i-1,j)*sumvp...
                               + vm(i+1)*pv2(i+1,j)*(1-prot2)+pv2(i+1,j)*sumvm...
                               + pv2(i,j-1)*sumhp...
                               +hp(j-1)*ph2(i,j-1)*prot2)*(1-pv2(i,j))...
                               -((ph1(i-1,j)+ph2(i-1,j)+pv1(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*prot2...
                               +(ph1(i+1,j)+ph2(i+1,j)+pv1(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*prot2...
                               +(ph1(i,j-1)+ph2(i,j-1)+pv1(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*(1-prot2)...
                               )*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((hp(j-1)*ph1(i,j-1)*(1-prot1)+ph1(i,j-1)*sumhp...
                               +...
                               + ph1(i-1,j)*sumvp + ph1(i+1,j)*sumvm...
                               +vp(i-1)*pv1(i-1,j)*prot1 + vm(i+1)*pv1(i+1,j)*prot1)*(1-ph1(i,j))...
                               -((ph2(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*(1-prot1)...
                               +(ph2(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*(1-prot1)...
                               +(ph2(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*prot1...
                               )*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((hp(j-1)*ph2(i,j-1)*(1-prot2)+ph2(i,j-1)*sumhp...
                              ...
                               + ph2(i-1,j)*sumvp + ph2(i+1,j)*sumvm...
                               +vp(i-1)*pv2(i-1,j)*prot2 + vm(i+1)*pv2(i+1,j)*prot2)*(1-ph2(i,j))...
                               -((ph1(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*(1-prot2)...
                               +(ph1(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*(1-prot2)...
                               +(ph1(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*prot2...
                               )*ph2(i,j));
                           
            elseif(i==1 && j ==1)
                 sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((...
                               + vm(i+1)*pv1(i+1,j)*(1-prot1)+pv1(i+1,j)*sumvm...
                               + pv1(i,j+1)*sumhm...
                               +hm(j+1)*ph1(i,j+1)*prot1)*(1-pv1(i,j))...
                               -(...
                               +(ph2(i+1,j)+ph1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*prot1...
                               ...
                               +(ph2(i,j+1)+ph1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*(1-prot1))*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((...
                               + vm(i+1)*pv2(i+1,j)*(1-prot2)+pv2(i+1,j)*sumvm...
                               + pv2(i,j+1)*sumhm...
                               + hm(j+1)*ph2(i,j+1)*prot2)*(1-pv2(i,j))...
                               -(...
                               +(ph1(i+1,j)+ph2(i+1,j)+pv1(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*prot2...
                               ...
                               +(ph1(i,j+1)+ph2(i,j+1)+pv1(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*(1-prot2))*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((...
                               + hm(j+1)*ph1(i,j+1)*(1-prot1)+ph1(i,j+1)*sumhm...
                               + ph1(i+1,j)*sumvm...
                               + vm(i+1)*pv1(i+1,j)*prot1)*(1-ph1(i,j))...
                               -(...
                               +(ph2(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*(1-prot1)...
                               ...
                               +(ph2(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*prot1)*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((...
                               + hm(j+1)*ph2(i,j+1)*(1-prot2)+ph2(i,j+1)*sumhm...
                               + ph2(i+1,j)*sumvm...
                               + vm(i+1)*pv2(i+1,j)*prot2)*(1-ph2(i,j))...
                               -(...
                               +(ph1(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*(1-prot2)...
                               ...
                               +(ph1(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*prot2)*ph2(i,j));
            elseif(i == 1 && j == N)
                 sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((...
                               + vm(i+1)*pv1(i+1,j)*(1-prot1)+pv1(i+1,j)*sumvm...
                               + pv1(i,j-1)*sumhp...
                               +hp(j-1)*ph1(i,j-1)*prot1)*(1-pv1(i,j))...
                               -(...
                               +(ph2(i+1,j)+ph1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*prot1...
                               +(ph2(i,j-1)+ph1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*(1-prot1)...
                               )*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((...
                               + vm(i+1)*pv2(i+1,j)*(1-prot2)+pv2(i+1,j)*sumvm...
                               + pv2(i,j-1)*sumhp...
                               +hp(j-1)*ph2(i,j-1)*prot2)*(1-pv2(i,j))...
                               -(...
                               +(ph1(i+1,j)+ph2(i+1,j)+pv1(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*prot2...
                               +(ph1(i,j-1)+ph2(i,j-1)+pv1(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*(1-prot2)...
                               )*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((hp(j-1)*ph1(i,j-1)*(1-prot1)+ph1(i,j-1)*sumhp...
                               ...
                               + ph1(i+1,j)*sumvm...
                               + vm(i+1)*pv1(i+1,j)*prot1)*(1-ph1(i,j))...
                               -(...
                               +(ph2(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv2(i+1,j) + vm(i+1)*pv1(i+1,j)*(1-prot1)...
                               +(ph2(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*prot1...
                               )*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((hp(j-1)*ph2(i,j-1)*(1-prot2)+ph2(i,j-1)*sumhp...
                               ...
                               + ph2(i+1,j)*sumvm...
                               + vm(i+1)*pv2(i+1,j)*prot2)*(1-ph2(i,j))...
                               -(...
                               +(ph1(i+1,j)+pv1(i+1,j)+pv2(i+1,j))*sumvm + vm(i+1)*pv1(i+1,j) + vm(i+1)*pv2(i+1,j)*(1-prot2)...
                               +(ph1(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*prot2...
                               )*ph2(i,j));
            elseif(i == M && j == 1)
                 sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((vp(i-1)*pv1(i-1,j)*(1-prot1)+pv1(i-1,j)*sumvp...
                               ...
                               + pv1(i,j+1)*sumhm...
                               + hm(j+1)*ph1(i,j+1)*prot1)*(1-pv1(i,j))...
                               -((ph2(i-1,j)+ph1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*prot1...
                               ...
                               ...
                               +(ph2(i,j+1)+ph1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*(1-prot1))*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((vp(i-1)*pv2(i-1,j)*(1-prot2)+pv2(i-1,j)*sumvp...
                               ...
                               + pv2(i,j+1)*sumhm...
                               + hm(j+1)*ph2(i,j+1)*prot2)*(1-pv2(i,j))...
                               -((ph1(i-1,j)+ph2(i-1,j)+pv1(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*prot2...
                              ...
                               ...
                               +(ph1(i,j+1)+ph2(i,j+1)+pv1(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*(1-prot2))*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((...
                               + hm(j+1)*ph1(i,j+1)*(1-prot1)+ph1(i,j+1)*sumhm...
                               + ph1(i-1,j)*sumvp ...
                               +vp(i-1)*pv1(i-1,j)*prot1)*(1-ph1(i,j))...
                               -((ph2(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*(1-prot1)...
                               ...
                               ...
                               +(ph2(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph2(i,j+1) + hm(j+1)*ph1(i,j+1)*prot1)*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((...
                               + hm(j+1)*ph2(i,j+1)*(1-prot2)+ph2(i,j+1)*sumhm...
                               + ph2(i-1,j)*sumvp...
                               +vp(i-1)*pv2(i-1,j)*prot2)*(1-ph2(i,j))...
                               -((ph1(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*(1-prot2)...
                               ...
                               ...
                               +(ph1(i,j+1)+pv1(i,j+1)+pv2(i,j+1))*sumhm + hm(j+1)*ph1(i,j+1) + hm(j+1)*ph2(i,j+1)*prot2)*ph2(i,j));
            elseif(i == M && j == N)
                 sumvp = 0;
                sumvm = 0;
                sumhp = 0;
                sumhm = 0;
                
                if(i > 2)
                    for a = 1:i-2
                        sumvp = sumvp + vp(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(i < M-1)
                    for a = i+2:M
                        sumvm = sumvm + vm(a)*(pv1(a,j) + pv2(a,j));
                    end
                end
                
                if(j > 2)
                    for a = 1:j-2
                        sumhp = sumhp + hp(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                if(j<N-1)
                    for a = j+2:N
                        sumhm = sumhm + hm(a)*(ph1(i,a) + ph2(i,a));
                    end
                end
                
                pv1_new(i,j) = pv1(i,j) + dt*((vp(i-1)*pv1(i-1,j)*(1-prot1)+pv1(i-1,j)*sumvp...
                               ...
                               + pv1(i,j-1)*sumhp...
                               +hp(j-1)*ph1(i,j-1)*prot1)*(1-pv1(i,j))...
                               -((ph2(i-1,j)+ph1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*prot1...
                               ...
                               +(ph2(i,j-1)+ph1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*(1-prot1)...
                               )*pv1(i,j));
                           
                pv2_new(i,j) = pv2(i,j) + dt*((vp(i-1)*pv2(i-1,j)*(1-prot2)+pv2(i-1,j)*sumvp...
                               ...
                               + pv2(i,j-1)*sumhp...
                               +hp(j-1)*ph2(i,j-1)*prot2)*(1-pv2(i,j))...
                               -((ph1(i-1,j)+ph2(i-1,j)+pv1(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*prot2...
                               ...
                               +(ph1(i,j-1)+ph2(i,j-1)+pv1(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*(1-prot2)...
                               )*pv2(i,j));
                           
                ph1_new(i,j) = ph1(i,j) + dt*((hp(j-1)*ph1(i,j-1)*(1-prot1)+ph1(i,j-1)*sumhp...
                              ...
                               + ph1(i-1,j)*sumvp...
                               +vp(i-1)*pv1(i-1,j)*prot1)*(1-ph1(i,j))...
                               -((ph2(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv2(i-1,j) + vp(i-1)*pv1(i-1,j)*(1-prot1)...
                               ...
                               +(ph2(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph2(i,j-1) + hp(j-1)*ph1(i,j-1)*prot1...
                               )*ph1(i,j));
                           
                ph2_new(i,j) = ph2(i,j) + dt*((hp(j-1)*ph2(i,j-1)*(1-prot2)+ph2(i,j-1)*sumhp...
                               ...
                               + ph2(i-1,j)*sumvp...
                               +vp(i-1)*pv2(i-1,j)*prot2)*(1-ph2(i,j))...
                               -((ph1(i-1,j)+pv1(i-1,j)+pv2(i-1,j))*sumvp + vp(i-1)*pv1(i-1,j) + vp(i-1)*pv2(i-1,j)*(1-prot2)...
                               ...
                               +(ph1(i,j-1)+pv1(i,j-1)+pv2(i,j-1))*sumhp + hp(j-1)*ph1(i,j-1) + hp(j-1)*ph2(i,j-1)*prot2...
                              )*ph2(i,j));
                
            end
         
        end 
    end
       ph1 = ph1_new;
       ph2 = ph2_new;
       pv1 = pv1_new;
       pv2 = pv2_new;
       
       if mod(k,50)==0
          figure(k)
          surf(pv2+ph2)
          set(gca,'fontsize',20)
          axis([1 N 1 M 0 1+.1])
          drawnow
%         figure(1)
%         surf(pv2 + ph2)
%         set(gca,'fontsize',20)
%         axis([1 N 1 M 0 1+.1])
%         drawnow
%         F(k) = getframe(gcf);
%         writeVideo(vidfile,F(k));
       end
       
end
%  close(vidfile)

 



